"""major refactor

Revision ID: 07a6a2d1d742
Revises: 
Create Date: 2025-06-24 23:57:24.706158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07a6a2d1d742'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('lastMessageDate', sa.DateTime(), nullable=False),
    sa.Column('brief', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('inboxStatus', sa.Boolean(), nullable=False),
    sa.Column('draftStatus', sa.Boolean(), nullable=False),
    sa.Column('sentStatus', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_done', 'threads', ['done'], unique=False)
    op.create_index('ix_threads_draft_status', 'threads', ['draftStatus'], unique=False)
    op.create_index('ix_threads_inbox_status', 'threads', ['inboxStatus'], unique=False)
    op.create_index('ix_threads_last_message_date', 'threads', ['lastMessageDate'], unique=False)
    op.create_index('ix_threads_sent_status', 'threads', ['sentStatus'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accountId', sa.Integer(), nullable=False),
    sa.Column('accountToken', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('lastDeltaToken', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('address_has_threads',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['email_addresses.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('address_id', 'thread_id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('threadId', sa.Integer(), nullable=False),
    sa.Column('createdTime', sa.DateTime(), nullable=False),
    sa.Column('lastModifiedTime', sa.DateTime(), nullable=True),
    sa.Column('sentAt', sa.DateTime(), nullable=False),
    sa.Column('receivedAt', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('fromId', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('inReplyTo', sa.String(), nullable=True),
    sa.Column('emailLabel', sa.String(), nullable=False),
    sa.Column('threadIndex', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['threadId'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emails_email_label', 'emails', ['emailLabel'], unique=False)
    op.create_index('ix_emails_sent_at', 'emails', ['sentAt'], unique=False)
    op.create_index('ix_emails_thread_id', 'emails', ['threadId'], unique=False)
    op.create_table('email_bcc_addresses',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['email_addresses.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('email_id', 'address_id')
    )
    op.create_table('email_cc_addresses',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['email_addresses.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('email_id', 'address_id')
    )
    op.create_table('email_reply_to_addresses',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['email_addresses.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('email_id', 'address_id')
    )
    op.create_table('email_to_addresses',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['email_addresses.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('email_id', 'address_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_to_addresses')
    op.drop_table('email_reply_to_addresses')
    op.drop_table('email_cc_addresses')
    op.drop_table('email_bcc_addresses')
    op.drop_index('ix_emails_thread_id', table_name='emails')
    op.drop_index('ix_emails_sent_at', table_name='emails')
    op.drop_index('ix_emails_email_label', table_name='emails')
    op.drop_table('emails')
    op.drop_table('address_has_threads')
    op.drop_table('users')
    op.drop_index('ix_threads_sent_status', table_name='threads')
    op.drop_index('ix_threads_last_message_date', table_name='threads')
    op.drop_index('ix_threads_inbox_status', table_name='threads')
    op.drop_index('ix_threads_draft_status', table_name='threads')
    op.drop_index('ix_threads_done', table_name='threads')
    op.drop_table('threads')
    op.drop_table('email_addresses')
    # ### end Alembic commands ###
