"""Initial schema

Revision ID: 3f51ffb2f992
Revises: 
Create Date: 2025-06-21 11:34:36.230725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f51ffb2f992'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_account_id'), table_name='threads')
    op.create_index('ix_threads_accountId', 'threads', ['accountId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_threads_accountId', table_name='threads')
    op.create_index(op.f('ix_threads_account_id'), 'threads', ['accountId'], unique=False)
    # ### end Alembic commands ###
