"""forget to mark from id as a foreign key

Revision ID: 94357dc87fac
Revises: eb56ac9741e2
Create Date: 2025-06-25 16:08:36.670009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94357dc87fac'
down_revision: Union[str, Sequence[str], None] = 'eb56ac9741e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'emails', 'email_addresses', ['fromId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    # ### end Alembic commands ###
