"""add updated/deleted delta tokens to users

Revision ID: ee66d23a1be8
Revises: 67d6540f23e7
Create Date: 2025-08-13 19:02:24.351637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee66d23a1be8'
down_revision: Union[str, Sequence[str], None] = '67d6540f23e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastUpdatedDeltaToken', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastDeletedDeltaToken', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastDeletedDeltaToken')
    op.drop_column('users', 'lastUpdatedDeltaToken')
    # ### end Alembic commands ###
