"""Added brief snippet to thread

Revision ID: f93e0e6ad1ac
Revises: 02f19f0e2598
Create Date: 2025-06-24 19:37:01.063858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93e0e6ad1ac'
down_revision: Union[str, Sequence[str], None] = '02f19f0e2598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('brief', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'brief')
    # ### end Alembic commands ###
