name: Deploy Worker to Fly.io
on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/fly-worker-deploy.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy worker
        run: flyctl deploy --remote-only --config backend/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}